# Generated by Django 5.2.3 on 2025-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_tests', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
