# Generated by Django 5.2.3 on 2025-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_tests', '0004_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
